# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestDefaultSuite():
  def setup_method(self):
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    #chrome_options.add_argument("--window-size=1920,1080")
    self.driver = webdriver.Chrome(chrome_options=chrome_options)
    #self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self):
    self.driver.quit()

  def test_australia(self):
    # Test name: Australia
    # Step # | name | target | value
    # 1 | open | https://www.health.gov.au/resources/total-covid-19-tests-conducted-and-results |
    self.driver.get("https://www.health.gov.au/resources/total-covid-19-tests-conducted-and-results")
    # 2 | waitForElementVisible | css=.ng-scope:nth-child(1) > .ng-binding:nth-child(2) | 300000
    WebDriverWait(self.driver, 300000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".ng-scope:nth-child(1) > .ng-binding:nth-child(2)")))
    # 3 | storeText | css=.ng-scope:nth-child(1) > .ng-binding:nth-child(2) | tests
    self.vars["tests"] = self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(1) > .ng-binding:nth-child(2)").text
    self.vars["country"] = "Australia"
    # 4 | close |  |
    self.driver.close()

  def test_unitedArabEmirates(self):
    # Test name: United Arab Emirates
    # Step # | name | target | value
    # 1 | open | https://fcsa.gov.ae/en-us/Pages/Covid19/UAE-Covid-19-Updates.aspx |
    self.driver.get("https://fcsa.gov.ae/en-us/Pages/Covid19/UAE-Covid-19-Updates.aspx")
    # 2 | waitForElementVisible | css=.total_tests > .numbers | 300000
    WebDriverWait(self.driver, 300000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".total_tests > .numbers")))
    # 3 | storeText | css=.total_tests > .numbers | tests
    self.vars["tests"] = self.driver.find_element(By.CSS_SELECTOR, ".total_tests > .numbers").text
    self.vars["country"] = "Emirates"
    # 4 | close |  |
    self.driver.close()


country_list = []

australia = TestDefaultSuite()
australia.setup_method()
australia.test_australia()
australia.teardown_method()
australia.vars

country_list.append(australia.vars)

emirates = TestDefaultSuite()
emirates.setup_method()
emirates.test_unitedArabEmirates()
emirates.teardown_method()
emirates.vars

country_list.append(emirates.vars)

with open("list_data.txt", 'w', encoding="utf-8") as f:
                            for item in country_list:
                                f.write("%s\n" % item)
                            f.close()
